import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <div className="flex flex-grow">
          <Sidebar />
          <div className="bg-teal-50 shadow-sm border border-gray-200 flex-grow my-2 mr-2 rounded-lg">
            <main className="max-w-7xl p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
